import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { DarkModeContextProvider } from "@/contexts/darkModeContext";
import { SectionRefContextProvider } from "@/contexts/sectionRefContext";
import { SearchBlogContextProvider } from "@/contexts/searchBlogContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Coding with Mufid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${poppins.className || "font-sans"} dark:bg-[#1a1a1a] bg-white overflow-x-hidden`}>
        <DarkModeContextProvider>
          <SectionRefContextProvider>
            <SearchBlogContextProvider>{children}</SearchBlogContextProvider>
          </SectionRefContextProvider>
        </DarkModeContextProvider>
      </body>
    </html>
  );
}
